rails_and_node/frontend/config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  get '/list', to: 'hotels#list'
  get '/filter/:filter_str', to: 'hotels#filter'
  root 'hotels#index'
end

rails_and_node/frontend/app/models/hotel.rb
class Hotel
  include Her::Model
end

rails_and_node/frontend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_and_node/frontend/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :find_hotel, only: [:edit, :update, :destroy]

  def index
  end

  def list
    @hotels = Hotel.all
  end

  def edit
  end

  def filter
    hotels = Array.new
    Hotel.where(filter: params.require(:filter_str)).all.each do |h|
      hotels.push(h.attributes)
    end
    render :json => hotels
  end

  def update
    hotel_params.each do |name, val|
      @hotel.send("#{name}=",val)
    end

    if @hotel.save
      redirect_to list_path
    else
      render 'edit'
    end
  end

  def new
    @hotel = Hotel.new
    @hotel.name = ""
    @hotel.address = ""
    @hotel.starRating = 0;
    @hotel.accomodationType = ""
    render 'edit'
  end

  def create
    @hotel = Hotel.new
    hotel_params.each do |name, val|
      @hotel.send("#{name}=",val)
    end

    if @hotel.save
      redirect_to list_path
    else
      render 'edit'
    end
  end

  def destroy
    @hotel.destroy
    redirect_to list_path
  end

  private
    def find_hotel
      @hotel = Hotel.find(params[:id])
      @hotel.id = @hotel._id
    end

    def hotel_params
      params.require(:hotel).permit(:name, :address, :accomodationType, :starRating)
    end

end

rails_and_node/frontend/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_and_node/frontend/app/helpers/hotels_helper.rb
module HotelsHelper
end

rails_and_node/frontend/app/views/hotels/_hotelsform.html.erb
<div class="form-group">
<%= simple_form_for @hotel do |f| %>
  <%= f.input :name, required: true, label: "Name", :input_html => { :class => "form-control"} %>
  <%= f.input :address, required: true, label: "Address", :input_html => { :class => "form-control"} %>
  <%= f.input :accomodationType, required: true, label: "Accomodation type", :input_html => { :class => "form-control"} %>
  <%= f.input :starRating, required: true, collection: 1..5, label: "Rating", :input_html => { :class => "form-control"} %>
  <br />
  <%= link_to "Back", list_path, class:"btn btn-default" %>
  <%= f.button :submit, :class => "btn btn-default" %>
<% end %>
</div>

rails_and_node/frontend/app/views/hotels/edit.html.erb
<div class="container" role="main">
  <%= render 'hotelsform' %>
</div>

rails_and_node/frontend/app/views/hotels/index.html.erb
<div class="container" role="main">
  <%= link_to "Edit Hotels", list_path, class:"btn btn-default" %>
  <div class="form-group">
    <label for="search">Search:</label>
    <input type="text" id="search" class="form-control"/>
  </div>
  <div class="progress" style="visibility:hidden" id="progressBar">
    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
    </div>
  </div>
  <div id="filtered" class="list-group">
  </div>
</div>

rails_and_node/frontend/app/views/hotels/list.html.erb
<div class="container" role="main">
  <div class="list-group">
    <% @hotels.each do |hotel| %>
      <div class="list-group-item">
        <h4 class="list-group-item-heading">
          <%= hotel.name %>
        </h4>
        <p class="list-group-item-text">
          <%= hotel.address %>
        </p>
	<%= link_to "", edit_hotel_path(hotel._id), class:"btn btn-default glyphicon glyphicon-edit" %>
	<%= link_to "", hotel_path(hotel._id), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-default glyphicon glyphicon-remove" %>
      </div>
    <% end %>
  </div>
  <%= link_to "New Hotel", new_hotel_path, class:"btn btn-default" %>
  <%= link_to "Back", root_path, class:"btn btn-default" %>
</div>

rails_and_node/frontend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frontend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>